[package]
name = "ai"
version = "0.1.0"
authors = []
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nn = { git = "https://github.com/pro465/nn-rs.git", tag = "v0.2.1" }
